### ISSUE TITLE
question:What does argument needed do?

### ISSUE THREAD

**Issue by mgolisch** [qdore/Mutate#101]
it seems that my script is not evauated without input even with that unchecked.
So what is it good for?
or rather: how can i make a script evaulated even with no input specified?

**Comment by benfalk** [comment]
Without double checking with the code I think it does two things.  It waits until you press to execute and only runs the script once if you have an argument required.  If you don't it runs your script over and over with each key stroke and takes it output to build up a list of suggestions.  Perhaps the best example is with the `google_translate.py` options populate.  I have used this personally to make my own little spell corrector:  https://github.com/benfalk/dotfiles/blob/master/config/Mutate/scripts/spell/spell.sh

Without knowing more of your needs I would suggest maybe creating a `run` keyword and have it switch off of a required input.  Maybe something like this

```
run my-script
```
