### ISSUE TITLE
translate didn't work 

### ISSUE THREAD

**Issue by SolidFaker** [qdore/Mutate#123]
So I type “tr work" and it shows nothing.

**Comment by dmp593** [comment]
same here!

**Comment by moeinrahimi** [comment]
same as others

**Comment by brunobarran** [comment]
same!

**Comment by chaoxu** [comment]
Google translate changes it's service and only send back a single word.
One way to fix is remove everything after `get_page = json.loads(get_page)` and add

```
    print '[' + get_page + ']'
    print 'command=copy'
    print 'icon='
    print 'subtext='
```

**Comment by SolidFaker** [comment]
thx!

2016年6月2日 下午3:40于 Chao Xu notifications@github.com写道：

**Comment by moeinrahimi** [comment]
@chaoxu thanks for your reply, just which file should be edited?

**Comment by chaoxu** [comment]
`config/scripts/googletranslate/google_translate.py`

**Comment by samundra** [comment]
For those who are looking for final script, you may find the final script here. https://gist.github.com/samundra/d07bd2e312f7c3d0b65de4b68c91b22d

_Don't forget to change the `target language` to your own liking._

**Comment by YanB25** [comment]
I've already change the code as @samundra  said above. It still doesn't work.
I type in the terminal
`$ mutate`
and try "tr work"
and I see the errors as below
```Traceback (most recent call last):
  File "/home/yb/.config/Mutate/scripts/googletranslate/google_translate.py", line 51, in <module>
    response = urllib2.urlopen(response)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden```
thx a lot

**Comment by samundra** [comment]
@YanB25 The response has `403 Forbidden` error.

This could possibly be due to various reasons. Finding the root cause needs more debugging. However you can start to debug from there. For reference see https://stackoverflow.com/questions/5871710/translate-url-with-google-translate-from-python-script
