### ISSUE TITLE
User .desktop files, incorrect handling.

### ISSUE THREAD

**Issue by Fordi** [qdore/Mutate#126]
Environment: Ubuntu 16.04, dm=MATE

Preconditions:
- ~/.local/share/applications/Slack.desktop :
  # !/usr/bin/env xdg-open
  
  [Desktop Entry]
  Version=1.0
  Terminal=false
  Type=Application
  Name=Chrome App
  Exec=/opt/google/chrome/google-chrome --app=https://slack.com/
  Icon=/home/user/.local/share/icons/hicolor/256x256/apps/chrome-slack.png
  StartupWMClass=slack.com__messages_company
- ![~/.local/share/icons/hicolor/256x256/apps/chrome-slack.png](https://cloud.githubusercontent.com/assets/116676/15150339/c5346cf6-169a-11e6-9c27-4dbe40954865.png)

Test procedure:
- Open Mutate
- Type "Slack"
  - Expected: Slack icon appears alongside name and shortcut
  - Actual: Generic icon appears
- Press enter
  - Expected: Chrome launches a new window and session, starting at https://slack.com
  - Actual: A new, blank Chrome tab opens

**Comment by Fordi** [comment]
I'll note, there's a simple solution for the second test condition: under linux environments, execution of .desktop files should be via xdg-open, not via the parsed Exec=... line.   This will ensure your app will behave consistently with the rest of the linux ecosystem.

**Comment by inoyatov** [comment]
@Fordi did you get some work around? Do you have solution for your situation?

**Comment by Luxian** [comment]
Any updates regarding this?
