### ISSUE TITLE
Error: PPA repository does not have a Release file.

### ISSUE THREAD

**Issue by kleinfreund** [qdore/Mutate#138]
An error is produced when trying to install Mutate with apt on Ubuntu:

```
sudo add-apt-repository ppa:mutate/ppa
```
works fine, but the next step fails:

```
$ sudo apt update
Ign:16 http://ppa.launchpad.net/mutate/ppa/ubuntu xenial InRelease
# ...
Err:21 http://ppa.launchpad.net/mutate/ppa/ubuntu xenial Release
  404  Not Found
# ...
E: The repository 'http://ppa.launchpad.net/mutate/ppa/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
I’m on Ubuntu 16.04.

**Comment by samundra** [comment]
<img width="827" alt="screen shot 2017-03-17 at 23 59 01" src="https://cloud.githubusercontent.com/assets/760855/24054147/ccdba992-0b6d-11e7-976d-0af8b28dfef2.png">

There is no package for xenial see http://ppa.launchpad.net/mutate/ppa/ubuntu/dists/ Try with vivid or lower versions. Update your apt manually and it should work.

**Comment by samundra** [comment]
You can get `xenial` build from https://github.com/qdore/Mutate/issues/136#issuecomment-269070483 @kleinfreund

**Comment by kleinfreund** [comment]
Then the installation instructions are not up-to-date as this is not noted in the readme.

**Comment by samundra** [comment]
The one I suggested above is not the official package (I assume) and needs to be tested well. Maybe  you should try to send PRs with your updated instructions and could be handy for others.
