### ISSUE TITLE
does not support chinese input rime

### ISSUE THREAD

**Issue by weejulius** [qdore/Mutate#2]
Hi,

Is it possible support chinese input rime?

**Comment by CharellKing** [comment]
我使用了搜狗for linux，在mutate输入框中，不支持中文切换啊，我的中文切换快捷键是CTRL+SPACE，本人操作系统是linux mint

**Comment by tracyone** [comment]
ubuntu14.04.03 64bit
sogou pinyin 2.0.0.0068
无法输入中文。
