### ISSUE TITLE
How to change hotkeys

### ISSUE THREAD

**Issue by mifas** [qdore/Mutate#26]
Hi, Thank you for the superb awesome app. A small info i want to change the hotkeys.

I've edit through `~/.config/Mutate/config.ini` But i wanna get this form. How can I get this box?
![](https://camo.githubusercontent.com/c3379b25c59211c18aedc27e6105fa12a99e23b0/687474703a2f2f692e696d6775722e636f6d2f3168484c5936722e706e67)

**Comment by igorbrites** [comment]
Meta doesn't work for me on Ubuntu 14.04. It uses the Windows key a lot. There's a way to type Ctrl twice to open Mutate? My IDE uses almost all of hotkeys most used. =P

**Comment by LukasSommerTu** [comment]
Is it possible to use only the Windows/Super-Key as hotkey?

**Comment by fikovnik** [comment]
It is possible to have it Meta+space? I can't make it work.

**Comment by abbasalitmk** [comment]
Thanks bro...

**Comment by luizanao** [comment]
Its possible to use super(Meta) double tap as hotkey?

**Comment by kitt-cat** [comment]
@luizanao I've [found a workaround to open it on single-tap super](http://unix.stackexchange.com/q/214956/86821) via [xcape](https://github.com/alols/xcape).
