### ISSUE TITLE
how do i configure mutate?

### ISSUE THREAD

**Issue by shaunstanislaus** [qdore/Mutate#31]
1) how do i find the preference in mutate in ubuntu? 

2) i have installed the python-pip requirements for the calculator, i tried ctrl + D and did "1 + 1" it wasn't calculating like Alfred in Mac. what do i do after installing the calculator dependencies?

**Comment by randsonjs** [comment]
Type `preferences` and select preferences page. 

The calculator I don't know about her ;(

**Comment by shaunstanislaus** [comment]
i think the calculator part, we need to add it manually into the scripts in the preference. lets wait for the owner to reply on how-to use the calculator after installing the dependencies.

**Comment by qdore** [comment]
Have you do sudo pip install sympy?

**Comment by paternogbc** [comment]
Hi,

thanks a lot for this app! It is great and smoth! ;)

I have a simple question, how can I change the translate to a english dictionary?
And I have one problem. I cant configure my hotkey to lunch Mutate with preference. Everythime I change the default Contrl + D to my preference, it just recycle again to the defaulta when I try to lunch Mutate.

Wish you all the best

**Comment by shaunstanislaus** [comment]
qdore, yes i have installed sympy, so how do you make the calculator work?

**Comment by qdore** [comment]
@paternogbc You must press save after you change your hotkey.
About change the translate to a english dictionary, you should modify this file: ~/.config/Mutate/scripts/google_translate/google_translate.py.(It seems to be this)

**Comment by qdore** [comment]
@shaunstanislaus the calculator should work fine now, didn't it?

**Comment by paternogbc** [comment]
Hi, thanks for your reply.

I saved the preferences but still not working. ;(
The app is fantastic but Contrl + D in my keyboard is not so good.

Another questions is how do I setup for automatic start with login, because I have to start Mutate every time. 

All the best,
Gustavo
