### ISSUE TITLE
find function broken

### ISSUE THREAD

**Issue by orschiro** [qdore/Mutate#33]
Hi @qdore,

Many thanks for Mutate. What a promising launcher! I installed the latest -git version using [mutate-git](https://aur.archlinux.org/packages/mutate-git) for Arch Linux. However, the find function does not work:

![image](https://cloud.githubusercontent.com/assets/170947/6002608/2ead8806-aaf5-11e4-9bee-1bdf027968dc.png)

Do you have any idea what the issue is?

Thankfully,

Robert

**Comment by travs** [comment]
Same system as me, and I also experience this problem

**Comment by qdore** [comment]
Er... Run ~/.config/Mutate/script/find.py test 。See what error dispayed.

**Comment by orschiro** [comment]
@qdore 

This seems to work. I searched for `bla` and this is an excerpt of the result:

```
[arrow-black.png]
command=xdg-open /home/orschiro/GoogleDrive/Applications/PortableApps/FirefoxPortable/Data/profile/zotero/storage/XCWGP7D4/arrow-black.png
icon=image-png
subtext=/home/orschiro/GoogleDrive/Applications/PortableApps/FirefoxPortable/Data/profile/zotero/storage/XCWGP7D4/arrow-black.png
[bubble-t-black.png]
command=xdg-open /home/orschiro/GoogleDrive/Applications/PortableApps/FirefoxPortable/Data/profile/zotero/storage/VJJ3CPBT/bubble-t-black.png
icon=image-png
subtext=/home/orschiro/GoogleDrive/Applications/PortableApps/FirefoxPortable/Data/profile/zotero/storage/VJJ3CPBT/bubble-t-black.png
[bullet-black.png]
command=xdg-open /home/orschiro/GoogleDrive/Applications/PortableApps/FirefoxPortable/Data/profile/zotero/storage/VJJ3CPBT/bullet-black.png
```

**Comment by travs** [comment]
@qdore 

Same result for me. `find.py` works without errors

**Comment by qdore** [comment]
find.py is only work for python2, your python version is python3.You can change it with python3 grammar

**Comment by travs** [comment]
I just changed the first line of `find.py` from `#!/usr/bin/python` to `#!/usr/bin/python2` and it works :)

This raises the larger issue of distros (arch) which default to python 3.x when running `usr/bin/python`

**Comment by orschiro** [comment]
> I just changed the first line of find.py from #!/usr/bin/python to #!/usr/bin/python2 and it works :)

I can confirm the fix!

> This fixes the current issue, but raises the larger issue of distros (arch) which default to python 3.x when running usr/bin/python

I guess this should be addressed at the PKGBUILD level. I will suggest that on the AUR. 

Two small things I noticed:

* I searched for `find .pdf` which was very slow and too several minutes to show the results. Any ways to improve the speed of the find search or is this a machine-specific limitation?
* The result did not show the PDF filetype icon but an unknown generic one.

Maybe related to this output?

```
Traceback (most recent call last):
  File "/home/orschiro/.config/Mutate/scripts/find/find.py", line 20, in <module>
    icon = gio.File(str).query_info("standard::icon").get_icon().to_string()
gio.Error: Error when getting information for file '/home/orschiro/.gvfs': Transport endpoint is not connected
Traceback (most recent call last):
  File "/home/orschiro/.config/Mutate/scripts/find/find.py", line 20, in <module>
    icon = gio.File(str).query_info("standard::icon").get_icon().to_string()
gio.Error: Error when getting information for file '/home/orschiro/.gvfs': Transport endpoint is not connected
```

**Comment by codeThatThinks** [comment]
Hi, I'm the maintainer for the AUR package. I think it would be better just to update all scripts that require python2 to #!/usr/bin/python2 in the repo rather than have the PKGBUILD fix it at build time.

According to [this PEP](http://legacy.python.org/dev/peps/pep-0394/) referenced in issue #38, any python script that only works with Python 2 should use #!/usr/bin/python2 regardless of distro.
