### ISSUE TITLE
Search for programs installed after Mutate is opened

### ISSUE THREAD

**Issue by travs** [qdore/Mutate#37]
System: recently-updated Manjaro linux

Steps to reproduce:

1. Open Mutate
2. Install a new app
3. Search for the app in Mutate, and it's not there

If you close and reopen Mutate the app is found, but I want to leave Mutate open and forget about it while I install new packages/programs

**Comment by qdore** [comment]
Scan apps need time,when mutate starts, it scans. May be change in the future.
