### ISSUE TITLE
Use GitHub releases feature

### ISSUE THREAD

**Issue by codeThatThinks** [qdore/Mutate#39]
I'm not sure why there are binary packages in the master branch. We should probably instead use the releases feature so version numbers don't get confused.

After a release is tagged, contributors should be able to build packages based off of that commit and add them to the release by clicking edit.

**Comment by qdore** [comment]
Yes, brilliant!

**Comment by codeThatThinks** [comment]
How is versioning done at the moment? I see references to 2.3 and 2.3-0.fc21 in the /release folder.

**Comment by randsonjs** [comment]
Yeah :+1: Brilliant!

**Comment by codeThatThinks** [comment]
Added instructions for releases in the wiki, released v2.4
