### ISSUE TITLE
How to install it on Ubuntu 14.10?

### ISSUE THREAD

**Issue by fedotxxl** [qdore/Mutate#43]
>sudo add-apt-repository ppa:mutate/ppa
>sudo apt-get update
>sudo apt-get install mutate
>E: Unable to locate package mutate

>wget https://github.com/qdore/Mutate/raw/master/release/mutate_2.3.deb
>sudo apt-get install gdebi
>sudo gdebi mutate_2.3.deb
>This package is uninstallable
>Dependency is not satisfiable: fcitx-libs-qt5

I'm not Linux guru. I just don't understand why installing software is so painful?

**Comment by ishu3101** [comment]
I am also getting the same message when I install it on Linux Mint 16 32bit.

**Comment by andrefigueira** [comment]
Getting this same issue as well Ubuntu 16.04, fresh install

**Comment by chenjunboBUPT** [comment]
Getting this same issue as well Ubuntu 18.04
