### ISSUE TITLE
Mutate: One application may be running

### ISSUE THREAD

**Issue by matasarei** [qdore/Mutate#53]
Hello! I tried Mutate on Ubuntu Mate 14.04 and Korora 21 (Cinnamon), and I have the same problem on both. 
![2015-04-05 23 41 15](https://cloud.githubusercontent.com/assets/6638367/6998552/57e09df6-dbee-11e4-8796-1a64a55e99d4.png)

I just run Mutate once using menu or hotkey and it's works, but next time it says "One application may be running...". May be I misunderstood how to use it, some default hotkeys or something? Can you explain? Thanks!

**Comment by maxfrigge** [comment]
Same problem on Fedora 21.

**Comment by rodrigolopezguerra** [comment]
Are you sure it's a bug? did you check with 'ps ax | grep mutate' that is not actually running?

ctrl+d is the default shortcut

**Comment by codeThatThinks** [comment]
It looks like Mutate doesn't clean up its temp files in /tmp when killed. These are used to check if Mutate is already running, and if they still exist you'll see that error next time you try to run it.
