### ISSUE TITLE
Arithmetic operators in search term changes behaviour (context)

### ISSUE THREAD

**Issue by lee-kode** [qdore/Mutate#60]
Hi,

Mutate is a really great app but I did come across some weird behaviour.

I created a script to shortcut to JIRA tickets. This is the script:

    echo [$@]
    echo "command=xdg-open \"https://jira.fakedomain.com/jira/browse/$@\""
    echo "icon="
    echo "subtext=Search JIRA for $@"

Here is the entry in config.ini

    [jira]
    ScriptAddress=/home/lee/.config/Mutate/scripts/jira/jira.sh
    IconAddress=/home/lee/.config/Mutate/scripts/jira/jira.png
    HotKey=
    Argument=need

The JIRA ticket format is <project>-<tiket number>. Example: TDP-5432

When I type *jira TDP* everything is working as expected but when I type the - (minus/dash) the context changes from *jira* to default. I experimented with the other arithmetic operators and I get the same behaviour.

Other than above, I really enjoy using Mutate.

Thank You.

Lee Engel

**Comment by rafcamlet** [comment]
+1

**Comment by benfalk** [comment]
I have a similar problem.  I created a script to search for AWS instances.  As soon as I enter any digit it changes to the default of a Google search.

Here is the script I put together: https://github.com/benfalk/dotfiles/blob/master/config/Mutate/config.ini#L36-L40

**Comment by benfalk** [comment]
@rafcamlet @lee-kode I have a fix for this in as pull request https://github.com/qdore/Mutate/pull/94
