### ISSUE TITLE
Fedora install instructions are out of date

### ISSUE THREAD

**Issue by jkudish** [qdore/Mutate#63]
The installation instructions from the readme are out of date. Is there a different url to use for the rpm?

`$ sudo yum -y install https://github.com/qdore/Mutate/raw/master/release/Mutate-2.3-0.fc21.x86_64.rpm` results in:

```
Cannot open: https://github.com/qdore/Mutate/raw/master/release/Mutate-2.3-0.fc21.x86_64.rpm. Skipping.
Error: Nothing to do
```

**Comment by codeThatThinks** [comment]
Oops, looks like I forgot to update the install instructions when we switched to using the releases feature on Github. The correct url is https://github.com/qdore/Mutate/releases/download/v2.3/Mutate-2.3-0.fc21.x86_64.rpm

**Comment by jkudish** [comment]
Thanks!

**Comment by juanmacortes** [comment]
Hi, I installed and compile Mutate on Fedora 31 but after reboot, my Thinkpad mousepad and point pad stop running. 
Is there anything I can do to revert this issue and also, what could it go wrong during the installation?
