### ISSUE TITLE
Mutate搜索框 不支持fcitx?

### ISSUE THREAD

**Issue by eleveni386** [qdore/Mutate#7]
我用的fcitx-sougou 输入法, 在其他程序里面 输入都没问题, 
echo $QT_IM_MODULE
xim

有安装qt的支持

fcitx-frontend-qt4 已经是最新的版本了。
fcitx-frontend-qt4 被设置为手动安装。
fcitx-frontend-qt5 已经是最新的版本了。
fcitx-frontend-qt5 被设置为手动安装。

**Comment by CharellKing** [comment]
好吧，回去重启机器吧，没有重启机器的习惯
