### ISSUE TITLE
Execute custom commands

### ISSUE THREAD

**Issue by Fuhrmann** [qdore/Mutate#73]
Is there a way to execute custom commands?

I'm developing a pidgin plugin but I have to execute three line of codes when the user selects the desired buddy to talk and I dont think there is only one command to execute that.

Something like defining a custom function inside my *.py file and execute when the user select the option.

**Comment by codeThatThinks** [comment]
If you'd like to execute more than command, simply put those commands into a shell script or if you have a custom function, move it to a separate file. Then set command to the path to the script, i.e. ```command=~/.config/Mutate/scripts/pidgin/custom_function.py```

**Comment by codeThatThinks** [comment]
I admit though, the script api could use a little bit of work to make it better.

**Comment by Fuhrmann** [comment]
@codeThatThinks ok, thanks!

**Comment by Fuhrmann** [comment]
I created a custom file to execute as command, but I have another question: You send the arguments to the command? Because I am trying to get the arguments this way:

query = str(sys.argv[0])
or
query = str(sys.argv[1])

But it only return the file name in the '0' position.
