### ISSUE TITLE
Meta + Space to open Mutate

### ISSUE THREAD

**Issue by Dazix** [qdore/Mutate#91]
Hi, 
Is there any way how to use Meta (Windows key) + Space to open Mutate? 
I tried write shortcut directly to the config.ini file, but it's don't work.

**Comment by mauri870** [comment]
Hi, try open your mutate search bar and write preferences. In next window look for a whole line blank filled only with the shortcut field. Click on the shortcut field and digit Meta+space and press enter. Click save and will work

**Comment by Dazix** [comment]
Awesome it works!!! It was my bad, I tried modify hotkey field throught the hotkey input in right side form, but it didn't work. So thank you very much.
