### ISSUE TITLE
can't install on fedora 22

### ISSUE THREAD

**Issue by thecotne** [qdore/Mutate#92]
```
[cotne@cotneXPS13 ~]$ sudo dnf install https://github.com/qdore/Mutate/releases/download/v2.3/Mutate-2.3-0.fc21.x86_64.rpm
Last metadata expiration check performed 0:16:32 ago on Tue Oct  6 20:58:06 2015.
Error: nothing provides libboost_regex.so.1.55.0()(64bit) needed by Mutate-2.3-0.fc21.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
The downloaded packages were saved in cache till the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
```

**Comment by Limero** [comment]
The problem happens because the version of boost-regex packaged for Fedora 22 is of version 1.57.0 and Mutate wants 1.55.0.

**Comment by thecotne** [comment]
that's obvious but can i fix it? or it need to be fixed in source?

**Comment by rodrigolopezguerra** [comment]
@thecotne maybe is specified in the spec ?

**Comment by rodrigolopezguerra** [comment]
Download and compile:

cd ~/rpmbuild/SOURCES
wget https://raw.githubusercontent.com/qdore/Mutate/master/rpm/mutate.spec
wget https://github.com/qdore/Mutate/archive/master.zip
sudo yum-builddep -y mutate.spec
rpmbuild -bb mutate.spec
Then install it:

sudo yum -y install ~/rpmbuild/RPMS/x86_64/Mutate-2.3-0.fc21.x86_64.rpm
/usr/share/mutate/setup

works ok

**Comment by rodri042** [comment]
More simple:
Install http://rpm.pbone.net/index.php3/stat/4/idpl/28563737/dir/fedora_21/com/boost-regex-1.55.0-8.fc21.x86_64.rpm.html and retry, until qdore fixes the package.

**Comment by thecotne** [comment]
```
sudo dnf install ftp://ftp.muug.mb.ca/mirror/fedora/linux/updates/21/SRPMS/b/boost-1.55.0-8.fc21.src.rpm
Last metadata expiration check performed 0:18:55 ago on Sun Nov  8 23:02:58 2015.
Error: nothing provides bzip2-devel(armv7hl-32) needed by boost-1.55.0-8.fc21.src
(try to add '--allowerasing' to command line to replace conflicting packages)
The downloaded packages were saved in cache till the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
```

does not help
